# GenerateHeader.cmake
if(NOT EXISTS "${INPUT_HTML}")
    message(FATAL_ERROR "Input file ${INPUT_HTML} does not exist!")
endif()

# Read the raw hex data from the HTML file
file(READ "${INPUT_HTML}" hex_content HEX)

# Format the hex string into commas (e.g., 0x48, 0x65, ...)
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " array_content "${hex_content}")

# Build the final header file content using a raw string literal or C++ array
set(hpp_content "/* Generated by CMake - do not modify */
#pragma once
#include <vector>

namespace Resources {
    inline const std::vector<unsigned char> index_html = {
        ${array_content}
    };
}
")

# Write the file out to the generated folder
file(WRITE "${OUTPUT_HPP}" "${hpp_content}")
