if(NOT EXISTS "${INPUT_HTML}")
    message(FATAL_ERROR "Input file ${INPUT_HTML} does not exist!")
endif()

file(READ "${INPUT_HTML}" hex_content HEX)

string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " array_content "${hex_content}")

set(hpp_content "/* Generated by CMake - do not modify */
#pragma once
#include <string_view>

namespace Resources {
    inline constexpr char index_html_data[] = {
        ${array_content}
    };
    inline constexpr std::string_view index_html(index_html_data, sizeof(index_html_data));
}
")

file(WRITE "${OUTPUT_HPP}" "${hpp_content}")
