.PHONY: all clean useeplus

CXX := zig c++

ifneq (,$(shell command -v ccache 2>/dev/null))
    CXX := ccache $(CXX)
endif

CXXFLAGS := -std=c++2b -Wall -Wextra -g -fno-omit-frame-pointer -Wno-deprecated-declarations

SRC_DIR         := src
BUILD_DIR       := build
GEN_DIR         := generated
THIRD_PARTY_DIR := third_party

HTML_FILE     := $(SRC_DIR)/index.html
GENERATED_HPP := $(GEN_DIR)/index_html.hpp

USEEPLUS_DIR := $(THIRD_PARTY_DIR)/useeplus
USEEPLUS_INC := $(USEEPLUS_DIR)/include/useeplus
USEEPLUS_LIB := $(USEEPLUS_DIR)/build/libuseeplus.a

USOCKETS_LIB := $(USEEPLUS_DIR)/third_party/uSockets/uSockets.a
USOCKETS_INC := $(USEEPLUS_DIR)/third_party/uSockets/src
UWEBSOCKETS_INC := $(USEEPLUS_DIR)/third_party/uWebSockets/src

UNAME_S := $(shell uname -s)
UNAME_P := $(shell uname -p)

LDFLAGS := -Wl,--start-group $(USOCKETS_LIB) $(USEEPLUS_LIB) -Wl,--end-group -lz -lssl -lcrypto -lpthread

LIBUSB_APP_SRC := $(SRC_DIR)/libusb/mjpeg_server_main.cpp
LIBUSB_APP     := $(BUILD_DIR)/mjpeg_server

V4L2_APP_SRCS  := $(SRC_DIR)/v4l2/v4l2_mjpeg_server_main.cpp \
                  $(USEEPLUS_DIR)/src/v4l2_device.cpp \
                  $(USEEPLUS_DIR)/src/v4l2_video_source.cpp

V4L2_APP       := $(BUILD_DIR)/v4l2_mjpeg_server

APP_TARGETS    := $(LIBUSB_APP)

ifeq ($(UNAME_S),Linux)
    PLATFORM := LINUX
    CXXFLAGS += -pthread
    ifneq (,$(filter aarch64%,$(UNAME_P)))
        CXXFLAGS += -target aarch64-linux-gnu -mcpu=cortex-a76
    endif

    APP_TARGETS += $(V4L2_APP)

else ifeq ($(UNAME_S),Darwin)
    PLATFORM := MACOS
endif

LIBUSB_CFLAGS := $(shell pkg-config --cflags libusb-1.0)
LIBUSB_LIBS   := $(shell pkg-config --libs libusb-1.0)

LDFLAGS += $(LIBUSB_LIBS)

INCLUDES := -I$(USEEPLUS_INC) \
            -I$(GEN_DIR) \
            -isystem $(UWEBSOCKETS_INC) \
            -isystem $(USOCKETS_INC) \
            $(patsubst -I%,-isystem %,$(LIBUSB_CFLAGS))

ifeq ($(PLATFORM),MACOS)
    OSSL_CFLAGS := $(shell pkg-config --cflags openssl 2>/dev/null || echo "-I/opt/homebrew/opt/openssl@3/include")
    INCLUDES += $(patsubst -I%,-isystem %,$(OSSL_CFLAGS))
    LDFLAGS  += $(shell pkg-config --libs-only-L openssl 2>/dev/null || echo "-L/opt/homebrew/opt/openssl@3/lib")
endif

CORE_DEPS := $(BUILD_DIR)/.core_deps

all: useeplus $(GENERATED_HPP) $(APP_TARGETS)

$(CORE_DEPS): install-core-deps.sh
	@echo "Fetching third-party dependencies..."
	@mkdir -p $(BUILD_DIR)
	@./install-core-deps.sh
	@touch $@

useeplus: $(CORE_DEPS)
	@echo "Ensuring useeplus core library is built..."
	@$(MAKE) -C $(USEEPLUS_DIR)

$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

$(GENERATED_HPP): $(HTML_FILE)
	@mkdir -p $(GEN_DIR)
	@echo "/* Generated by Makefile - do not modify */" > $@
	@echo "#pragma once" >> $@
	@echo "#include <string_view>" >> $@
	@echo "" >> $@
	@echo "namespace Resources {" >> $@
	@echo "    inline constexpr char index_html_data[] = {" >> $@
	@hexdump -v -e '/1 "0x%02x, "' $< >> $@
	@echo "" >> $@
	@echo "    };" >> $@
	@echo "    inline constexpr std::string_view index_html(index_html_data, sizeof(index_html_data));" >> $@
	@echo "}" >> $@

$(LIBUSB_APP): $(LIBUSB_APP_SRC) $(USEEPLUS_LIB) $(GENERATED_HPP) | $(BUILD_DIR)
	@echo "Building libusb MJPEG server..."
	$(CXX) $(CXXFLAGS) $(INCLUDES) $< -o $@ $(LDFLAGS)

$(V4L2_APP): $(V4L2_APP_SRCS) $(USEEPLUS_LIB) $(GENERATED_HPP) | $(BUILD_DIR)
	@echo "Building V4L2 MJPEG server..."
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(V4L2_APP_SRCS) -o $@ $(LDFLAGS)

clean:
	rm -rf $(BUILD_DIR) $(GEN_DIR)
